# name = input("Enter your full  name: ")
phone_number = input("Enter your phone number: ")

# result = len(name)
# result = name.find("s")
# result = name.rfind("s")
# result = name.rfind("q")
# name = name.capitalize()
# name = name.upper()
# name = name.lower()
# result = name.isdigit()
# result = name.alpha()
# result = phone_number.count("-")
result = phone_number.replace("3","2")

print(result)